name: flutter_admob_native_ads
description: A Flutter plugin for displaying AdMob Native Ads with customizable layouts and SwiftUI-style declarative styling.
version: 1.0.2
homepage: https://github.com/tqc/flutter_admob_native_ads
repository: https://github.com/tqc/flutter_admob_native_ads

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  plugin:
    platforms:
      android:
        package: com.tqc.ads.flutter_admob_native_ads
        pluginClass: FlutterAdmobNativeAdsPlugin
      ios:
        pluginClass: FlutterAdmobNativeAdsPlugin
