name: flutter_admob_native_ads
description: A Flutter plugin for displaying AdMob Native Ads with customizable layouts and SwiftUI-style declarative styling.
<<<<<<< HEAD
version: 1.0.2+1
homepage: https://github.com/TQC-Solution/flutter_admob_native_ads
repository: https://github.com/TQC-Solution/flutter_admob_native_ads
=======
version: 1.0.3
homepage: https://github.com/tqc/flutter_admob_native_ads
repository: https://github.com/tqc/flutter_admob_native_ads
>>>>>>> 3a1bc15 (update readMe + change log)

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  plugin:
    platforms:
      android:
        package: com.tqc.ads.flutter_admob_native_ads
        pluginClass: FlutterAdmobNativeAdsPlugin
      ios:
        pluginClass: FlutterAdmobNativeAdsPlugin
